version: "3.3"

services:

  Load_Balancer:
    image: "haproxy"
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
  
  server1:
    image: serverapp
    environment:
      - APPID=server1
  
  server2:
    image: serverapp
    environment:
      - APPID=server2
  server3:
    image: serverapp
    environment:
      - APPID=server3
  
  server4:
    image: serverapp
    environment:
      - APPID=server4

  redis:
    image: redis
